---
dist: xenial
sudo: required

services:
  - docker

language: python
python: 3.5

branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - OS=archlinux_latest
  - OS=centos_7
  - OS=fedora_23
  - OS=fedora_24
  - OS=fedora_25
  - OS=fedora_26
  - OS=fedora_27
  - OS=fedora_28
  - OS=fedora_29
  - OS=debian_jessie
  - OS=debian_stretch
  - OS=ubuntu_trusty
  - OS=ubuntu_xenial
  - OS=ubuntu_bionic

before_install:
  - >-
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew upgrade openssl || brew install openssl || true
      brew upgrade python@3 || brew install python@3 || true
      brew upgrade md5sha1sum || brew install md5sha1sum || true
      virtualenv venv -p python
      source venv/bin/activate
      pip install ansible
    fi

install:
  - pip install ansible-galaxy-local-deps dcb==0.0.16
  - ansible-galaxy-local-deps-write

script:
  - >-
    dcb
    --upstreamgroup andrewrothstein
    --upstreamapp docker-ansible-role
    --pull ${OS}
    --write ${OS}
    --build ${OS}
    --push ${OS}
